[package]
name = "vectorstore-core"
version.workspace = true
edition = "2021"

[features]
default = []

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(feature, values("kube", "pgvector"))'] }
[dependencies]
async-trait = "0.1"
aws-config = { version = "1.10.1", features = ["behavior-version-latest"] }
aws-sdk-s3 = "1"
reqwest = { version = "0.12", features = ["json"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
serde_yaml = "0.9"
thiserror = "2"
tokio = { version = "1", features = ["sync", "time"] }
hevsearch-core = { git = "https://github.com/hev/search", rev = "1464e688186792c9a9fe38b4b3b4a6bfccdcae46", optional = true }

percent-encoding = "2"

[dev-dependencies]
axum = "0.8"
tokio = { version = "1", features = ["macros", "net", "rt"] }
