use std::collections::HashMap;
use std::env;
use std::fs;
use std::path::PathBuf;

const DEFAULT_TURBOPUFFER_REGION: &str = "aws-us-east-1";

#[derive(Debug, Clone)]
pub struct Config {
    pub drain_marker_path: PathBuf,
    pub aerospike_hosts: Option<String>,
    pub aerospike_namespace: String,
    pub aerospike_set_prefix: String,
    pub aerospike_cluster_name: Option<String>,
    pub s3_bucket: String,
    pub s3_region: String,
    pub s3_endpoint: Option<String>,
    /// Enables Kubernetes Index CR deletion when a namespace is hard-deleted.
    pub index_gc_enabled: bool,
    /// Enables gateway reads of Index CR policy such as snapshot facet fields.
    pub index_config_enabled: bool,
    /// Namespace containing Index CRs generated by the operator discovery loop.
    pub index_namespace: String,
    /// Namespace containing the default VectorStore and its credential Secret.
    pub vector_store_namespace: String,
    /// Static VectorStore config for standalone/local use. When set, the
    /// gateway does not require Kubernetes to resolve store configuration.
    pub stores_json: Option<String>,
    /// Base URL for Turbopuffer dashboard deep links.
    pub turbopuffer_dashboard_base_url: String,
    /// Namespace containing `ApiKey` resources. Defaults to the
    /// VectorStore namespace.
    pub keys_namespace: String,
    /// argon2id pepper for minted API keys (`LAYER_KEY_PEPPER`). Minting
    /// and verification of minted keys are disabled without it.
    pub key_pepper: Option<String>,
    /// Fixed-window cap on `/v2/keys/authenticate` calls per minute.
    pub keys_auth_rate_limit_per_min: u32,
    pub port: u16,
    pub database_url: Option<String>,
    pub pipeline_segment_size: usize,
    /// Attempts before permanently unfetchable pipeline chunks dead-letter.
    pub pipeline_chunk_dead_letter_max_attempts: u32,
    /// Backoff hint for workers between poisoned chunk retries.
    pub pipeline_chunk_dead_letter_backoff_ms: u64,
    pub metrics_backend_url: Option<String>,
    /// Enables AWS Cost Explorer reads for `/v2/cost`.
    pub aws_cost_explorer_enabled: bool,
    /// AWS region used for the Cost Explorer SDK client and response labels.
    pub aws_cost_region: String,
    /// Cost-allocation tag key used to scope Cost Explorer to the Layer stack.
    pub aws_cost_tag_key: String,
    /// Cost-allocation tag value used to scope Cost Explorer to the Layer stack.
    pub aws_cost_tag_value: String,
    /// Site label attached to AWS invoice cost lines.
    pub aws_cost_site: String,
    /// TTL for the S3 Cost Explorer cache. Defaults to one day.
    pub aws_cost_cache_ttl_seconds: u64,
    pub consistency_poll_interval_ms: u64,
    pub consistency_stable_poll_interval_ms: u64,
    pub consistency_safety_margin_ms: u64,
    /// Per-namespace facet fields to histogram when writing a snapshot.
    /// Parsed from `LAYER_FACET_FIELDS` as JSON: `{"ns":["field1","field2"]}`.
    /// Namespaces absent from this map produce no snapshots.
    pub facet_fields: HashMap<String, Vec<String>>,
    /// Floor on snapshot frequency per namespace. Defaults to 5 minutes.
    pub snapshot_min_interval_ms: u64,
    /// Period between Index CR facet-field refreshes. Defaults to 30s.
    pub facet_refresh_ms: u64,
    /// TTL (ms) for the in-memory pipeline-status cache. Defaults to 15s.
    /// Protects PostgreSQL from repeated status reads when the dashboard or
    /// KEDA polls the endpoint at sub-second intervals.
    pub pipeline_status_cache_ttl_ms: u64,
    /// Number of deterministic `_hevlayer_shard` partitions to stamp and
    /// fan out across after a namespace is migrated.
    pub shard_count: u64,
    /// Rows patched per embedded namespace init batch.
    pub init_backfill_batch_size: u32,
    /// Embedded namespace init scan/patch batches per second. `0` disables
    /// sleeping between batches.
    pub init_backfill_rps: u32,
    /// Maximum namespaces accepted by one federated `/v2/query` request.
    pub federated_query_max_namespaces: usize,
    /// Maximum namespace legs run concurrently by one federated `/v2/query`.
    pub federated_query_namespace_threads: usize,
    /// TTL (ms) for the `GET /v2/namespaces` response cache. Defaults to
    /// 10s — short enough to feel live, long enough to absorb dashboard
    /// polling without fanning out a per-namespace metadata call per row
    /// per refresh.
    pub namespace_list_cache_ttl_ms: u64,
    /// TTL for gateway-resolved query embeddings. Defaults to 60 seconds.
    pub embedding_cache_ttl_ms: u64,
    /// Static Agent specs for local/dev use. Production Kubernetes
    /// resolution populates the same in-memory registry.
    pub agents_json: Option<String>,
    /// Anonymous standalone telemetry. Enabled by default; disabled with
    /// `LAYER_TELEMETRY=off` or `DO_NOT_TRACK=1`.
    pub telemetry_enabled: bool,
    pub telemetry_endpoint: String,
    pub telemetry_state_path: Option<PathBuf>,
}

impl Config {
    pub fn from_env() -> Self {
        let index_namespace = env::var("LAYER_INDEX_NAMESPACE")
            .ok()
            .and_then(trimmed_non_empty)
            .unwrap_or_else(|| "default".to_string());
        let vector_store_namespace = env::var("LAYER_VECTORSTORE_NAMESPACE")
            .ok()
            .and_then(trimmed_non_empty)
            .unwrap_or_else(|| index_namespace.clone());
        let keys_namespace = env::var("LAYER_KEYS_NAMESPACE")
            .ok()
            .and_then(trimmed_non_empty)
            .unwrap_or_else(|| vector_store_namespace.clone());
        let turbopuffer_dashboard_base_url = env::var("LAYER_TURBOPUFFER_DASHBOARD_URL")
            .ok()
            .and_then(trimmed_non_empty)
            .unwrap_or_else(|| "https://turbopuffer.com".to_string());

        Self {
            drain_marker_path: env::var("LAYER_DRAIN_MARKER_PATH")
                .ok()
                .and_then(trimmed_non_empty)
                .map(PathBuf::from)
                .unwrap_or_else(|| PathBuf::from("/tmp/layer-gateway-draining")),
            keys_namespace,
            turbopuffer_dashboard_base_url,
            key_pepper: env::var("LAYER_KEY_PEPPER")
                .ok()
                .and_then(trimmed_non_empty),
            keys_auth_rate_limit_per_min: env::var("LAYER_KEYS_AUTH_RATE_LIMIT_PER_MIN")
                .ok()
                .and_then(|s| s.parse().ok())
                .filter(|limit| *limit > 0)
                .unwrap_or(120),
            aerospike_hosts: env::var("AEROSPIKE_HOSTS").ok().and_then(trimmed_non_empty),
            aerospike_namespace: env::var("AEROSPIKE_NAMESPACE")
                .unwrap_or_else(|_| "hevlayer".to_string()),
            aerospike_set_prefix: env::var("AEROSPIKE_SET_PREFIX")
                .unwrap_or_else(|_| "tpuf_".to_string()),
            aerospike_cluster_name: env::var("AEROSPIKE_CLUSTER_NAME").ok(),
            s3_bucket: env::var("S3_BUCKET").unwrap_or_else(|_| "hevlayer-wal".to_string()),
            s3_region: env::var("S3_REGION").unwrap_or_else(|_| "us-east-1".to_string()),
            s3_endpoint: env::var("S3_ENDPOINT").ok(),
            index_gc_enabled: env::var("LAYER_INDEX_GC_ENABLED")
                .ok()
                .and_then(|s| s.parse::<bool>().ok())
                .unwrap_or(false),
            index_config_enabled: env::var("LAYER_INDEX_CONFIG_ENABLED")
                .ok()
                .and_then(|s| s.parse::<bool>().ok())
                .unwrap_or(false),
            index_namespace,
            vector_store_namespace,
            stores_json: stores_json_from_env(),
            port: env::var("PORT")
                .unwrap_or_else(|_| "8080".to_string())
                .parse()
                .expect("PORT must be a valid u16"),
            database_url: env::var("DATABASE_URL").ok(),
            pipeline_segment_size: env::var("PIPELINE_SEGMENT_SIZE")
                .ok()
                .and_then(|s| s.parse::<usize>().ok())
                .filter(|size| *size > 0)
                .unwrap_or(10_000),
            pipeline_chunk_dead_letter_max_attempts: env::var(
                "PIPELINE_CHUNK_DEAD_LETTER_MAX_ATTEMPTS",
            )
            .ok()
            .and_then(|s| s.parse::<u32>().ok())
            .filter(|attempts| *attempts > 0)
            .unwrap_or(8),
            pipeline_chunk_dead_letter_backoff_ms: env::var(
                "PIPELINE_CHUNK_DEAD_LETTER_BACKOFF_MS",
            )
            .ok()
            .and_then(|s| s.parse::<u64>().ok())
            .unwrap_or(1_000),
            metrics_backend_url: env::var("METRICS_BACKEND_URL").ok(),
            aws_cost_explorer_enabled: env::var("LAYER_AWS_COST_EXPLORER_ENABLED")
                .ok()
                .and_then(|s| s.parse::<bool>().ok())
                .unwrap_or(true),
            aws_cost_region: env::var("LAYER_AWS_COST_REGION")
                .ok()
                .and_then(trimmed_non_empty)
                .unwrap_or_else(|| "us-east-1".to_string()),
            aws_cost_tag_key: env::var("LAYER_AWS_COST_TAG_KEY")
                .ok()
                .and_then(trimmed_non_empty)
                .unwrap_or_else(|| "Project".to_string()),
            aws_cost_tag_value: env::var("LAYER_AWS_COST_TAG_VALUE")
                .ok()
                .and_then(trimmed_non_empty)
                .unwrap_or_else(|| "hevlayer".to_string()),
            aws_cost_site: env::var("LAYER_AWS_COST_SITE")
                .ok()
                .and_then(trimmed_non_empty)
                .unwrap_or_else(|| "main".to_string()),
            aws_cost_cache_ttl_seconds: env::var("LAYER_AWS_COST_CACHE_TTL_SECONDS")
                .ok()
                .and_then(|s| s.parse().ok())
                .filter(|seconds| *seconds > 0)
                .unwrap_or(86_400),
            consistency_poll_interval_ms: env::var("CONSISTENCY_POLL_INTERVAL_MS")
                .ok()
                .and_then(|s| s.parse().ok())
                .unwrap_or(1000),
            consistency_stable_poll_interval_ms: env::var("CONSISTENCY_STABLE_POLL_INTERVAL_MS")
                .ok()
                .and_then(|s| s.parse().ok())
                .unwrap_or(60_000),
            consistency_safety_margin_ms: env::var("CONSISTENCY_SAFETY_MARGIN_MS")
                .ok()
                .and_then(|s| s.parse().ok())
                .unwrap_or(500),
            facet_fields: env::var("LAYER_FACET_FIELDS")
                .ok()
                .and_then(|s| serde_json::from_str::<HashMap<String, Vec<String>>>(&s).ok())
                .unwrap_or_default(),
            snapshot_min_interval_ms: env::var("LAYER_SNAPSHOT_MIN_INTERVAL_MS")
                .ok()
                .and_then(|s| s.parse().ok())
                .unwrap_or(300_000),
            facet_refresh_ms: env::var("LAYER_FACET_REFRESH_MS")
                .ok()
                .and_then(|s| s.parse().ok())
                .filter(|ms| *ms > 0)
                .unwrap_or(30_000),
            pipeline_status_cache_ttl_ms: env::var("PIPELINE_STATUS_CACHE_TTL_MS")
                .ok()
                .and_then(|s| s.parse().ok())
                .unwrap_or(15_000),
            shard_count: env::var("LAYER_SHARD_COUNT")
                .ok()
                .and_then(|s| s.parse::<u64>().ok())
                .filter(|count| *count > 0)
                .unwrap_or(crate::shards::DEFAULT_SHARD_COUNT),
            init_backfill_batch_size: env::var("LAYER_INIT_BACKFILL_BATCH_SIZE")
                .ok()
                .and_then(|s| s.parse::<u32>().ok())
                .filter(|count| *count > 0)
                .unwrap_or(1000),
            init_backfill_rps: env::var("LAYER_INIT_BACKFILL_RPS")
                .ok()
                .and_then(|s| s.parse::<u32>().ok())
                .unwrap_or(5),
            federated_query_max_namespaces: env::var("LAYER_FEDERATED_QUERY_MAX_NAMESPACES")
                .ok()
                .and_then(|s| s.parse::<usize>().ok())
                .filter(|count| *count > 0)
                .unwrap_or(512),
            federated_query_namespace_threads: env::var("LAYER_FEDERATED_QUERY_NAMESPACE_THREADS")
                .ok()
                .and_then(|s| s.parse::<usize>().ok())
                .filter(|count| *count > 0)
                .unwrap_or(16),
            namespace_list_cache_ttl_ms: env::var("NAMESPACE_LIST_CACHE_TTL_MS")
                .ok()
                .and_then(|s| s.parse().ok())
                .unwrap_or(10_000),
            embedding_cache_ttl_ms: env::var("LAYER_EMBED_CACHE_TTL_MS")
                .ok()
                .and_then(|s| s.parse().ok())
                .unwrap_or(60_000),
            agents_json: env::var("LAYER_AGENTS_JSON")
                .ok()
                .and_then(trimmed_non_empty),
            telemetry_enabled: telemetry_enabled(
                env::var("LAYER_TELEMETRY").ok().as_deref(),
                env::var("DO_NOT_TRACK").ok().as_deref(),
            ),
            telemetry_endpoint: env::var("LAYER_TELEMETRY_ENDPOINT")
                .ok()
                .and_then(trimmed_non_empty)
                .unwrap_or_else(|| "https://telemetry.hevlayer.com".to_string()),
            telemetry_state_path: env::var("LAYER_TELEMETRY_STATE_PATH")
                .ok()
                .and_then(trimmed_non_empty)
                .map(PathBuf::from)
                .or_else(default_telemetry_state_path),
        }
    }
}

fn stores_json_from_env() -> Option<String> {
    if let Some(path) = env::var("LAYER_STORE_FILE")
        .ok()
        .and_then(trimmed_non_empty)
    {
        return Some(
            fs::read_to_string(&path)
                .unwrap_or_else(|error| panic!("failed to read LAYER_STORE_FILE {path}: {error}")),
        );
    }
    if let Some(stores_json) = env::var("LAYER_STORE_JSON")
        .ok()
        .and_then(trimmed_non_empty)
    {
        return Some(stores_json.to_string());
    }
    if let Some(stores_json) = env::var("LAYER_STORES_JSON")
        .ok()
        .and_then(trimmed_non_empty)
    {
        eprintln!("warning: LAYER_STORES_JSON is deprecated; use LAYER_STORE_JSON");
        return Some(stores_json.to_string());
    }
    // TPUF_URL alone configures the default store — the turbopuffer region is
    // already encoded in the endpoint host, so no region field is synthesized.
    if let Some(url) = env::var("TPUF_URL").ok().and_then(trimmed_non_empty) {
        return Some(
            serde_json::json!({
                "default": {
                    "kind": "turbopuffer",
                    "endpoint": {"url": url},
                    "inboundAuth": {"mode": "deriveFromStore"}
                }
            })
            .to_string(),
        );
    }
    let region = env::var("TURBOPUFFER_REGION")
        .ok()
        .and_then(trimmed_non_empty)
        .unwrap_or_else(|| DEFAULT_TURBOPUFFER_REGION.to_string());
    Some(
        serde_json::json!({
            "default": {
                "kind": "turbopuffer",
                "endpoint": {
                    "url": "https://api.turbopuffer.com",
                    "region": region
                },
                "inboundAuth": {"mode": "deriveFromStore"}
            }
        })
        .to_string(),
    )
}

fn telemetry_enabled(layer_telemetry: Option<&str>, do_not_track: Option<&str>) -> bool {
    if do_not_track
        .map(|value| value.trim().eq_ignore_ascii_case("1"))
        .unwrap_or(false)
    {
        return false;
    }

    !matches!(
        layer_telemetry.map(|value| value.trim().to_ascii_lowercase()),
        Some(value) if matches!(value.as_str(), "0" | "false" | "no" | "off" | "disabled")
    )
}

fn default_telemetry_state_path() -> Option<PathBuf> {
    if let Some(state_home) = env::var("XDG_STATE_HOME").ok().and_then(trimmed_non_empty) {
        return Some(PathBuf::from(state_home).join("hevlayer/gateway-telemetry.json"));
    }
    env::var("HOME")
        .ok()
        .and_then(trimmed_non_empty)
        .map(|home| PathBuf::from(home).join(".local/state/hevlayer/gateway-telemetry.json"))
}

fn trimmed_non_empty(value: String) -> Option<String> {
    let value = value.trim();
    if value.is_empty() {
        None
    } else {
        Some(value.to_string())
    }
}

#[cfg(test)]
mod tests {
    use super::{telemetry_enabled, trimmed_non_empty};

    #[test]
    fn trimmed_non_empty_removes_surrounding_whitespace() {
        assert_eq!(
            trimmed_non_empty("  secret\n".to_string()),
            Some("secret".to_string())
        );
        assert_eq!(trimmed_non_empty("\r\n\t".to_string()), None);
    }

    #[test]
    fn telemetry_is_enabled_by_default_and_respects_opt_out() {
        assert!(telemetry_enabled(None, None));
        assert!(!telemetry_enabled(Some("off"), None));
        assert!(!telemetry_enabled(Some("FALSE"), None));
        assert!(!telemetry_enabled(None, Some("1")));
        assert!(telemetry_enabled(Some("on"), Some("0")));
    }
}
