apiVersion: v1
kind: Service
metadata:
  name: {{ include "layer.fullname" . }}-gateway
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "layer.labels" . | nindent 4 }}
    app.kubernetes.io/component: gateway
spec:
  type: ClusterIP
  selector:
    {{- include "layer.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: gateway
  ports:
    - name: http
      port: {{ .Values.gateway.port }}
      targetPort: http
