{{- $saName := include "layer.serviceAccountName" . }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "layer.fullname" . }}-gateway-agents
  labels:
    {{- include "layer.labels" . | nindent 4 }}
    app.kubernetes.io/component: gateway
rules:
  - apiGroups: ["hevlayer.com"]
    resources: ["agents"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "layer.fullname" . }}-gateway-agents
  labels:
    {{- include "layer.labels" . | nindent 4 }}
    app.kubernetes.io/component: gateway
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "layer.fullname" . }}-gateway-agents
subjects:
  - kind: ServiceAccount
    name: {{ $saName }}
    namespace: {{ .Release.Namespace }}
