{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "layer.fullname" . }}-gateway
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "layer.labels" . | nindent 4 }}
    app.kubernetes.io/component: gateway
  annotations:
    alb.ingress.kubernetes.io/group.name: {{ .Values.ingress.groupName | quote }}
    alb.ingress.kubernetes.io/group.order: {{ .Values.ingress.groupOrder | quote }}
    {{- if .Values.ingress.tags }}
    alb.ingress.kubernetes.io/tags: {{ .Values.ingress.tags | quote }}
    {{- end }}
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80},{"HTTPS":443}]'
    alb.ingress.kubernetes.io/ssl-redirect: "443"
    alb.ingress.kubernetes.io/healthcheck-path: /ready
    alb.ingress.kubernetes.io/healthcheck-protocol: HTTP
spec:
  ingressClassName: alb
  rules:
    - host: {{ .Values.ingress.host | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "layer.fullname" . }}-gateway
                port:
                  number: {{ .Values.gateway.port }}
{{- end }}
