{{- if and .Values.operator.enabled .Values.operator.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ default (printf "%s-operator" (include "layer.fullname" .)) .Values.operator.serviceAccount.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "layer.labels" . | nindent 4 }}
    app.kubernetes.io/component: operator
  {{- if .Values.operator.serviceAccount.roleArn }}
  annotations:
    eks.amazonaws.com/role-arn: {{ .Values.operator.serviceAccount.roleArn | quote }}
  {{- end }}
{{- end }}
