{{- if .Values.serviceAccount.create }}
{{- $gatewayServiceAccountName := include "layer.serviceAccountName" . }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $gatewayServiceAccountName }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "layer.labels" . | nindent 4 }}
  {{- if .Values.serviceAccount.roleArn }}
  annotations:
    eks.amazonaws.com/role-arn: {{ .Values.serviceAccount.roleArn | quote }}
  {{- end }}
{{- end }}
{{- if and .Values.dashboard.enabled .Values.dashboard.serviceAccount.create (ne (include "layer.dashboardServiceAccountName" .) (include "layer.serviceAccountName" .)) }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "layer.dashboardServiceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "layer.labels" . | nindent 4 }}
    app.kubernetes.io/component: dashboard
  {{- if .Values.dashboard.serviceAccount.roleArn }}
  annotations:
    eks.amazonaws.com/role-arn: {{ .Values.dashboard.serviceAccount.roleArn | quote }}
  {{- end }}
{{- end }}
